Policy:
  RestartPolicy: Always
  ImagePullPolicy: Always
All:
  targetPort: 8060
Gateway:
   RestPort: 8060
   gRPCPort: 50051
   NodePort: 30031
   DNS: log-gateway-src
   Image: docker.io/midaswr/gateway:latest
   DeploymentReplicas: 1
   CpuAverage: 70
   MinReplicas: 1
   MaxReplicas: 50
EventService:
  RestPort: 8040
  Image: docker.io/midaswr/event_service:latest
  DNS: log-event-src
  DeploymentReplicas: 1
  CpuAverage: 70
  MinReplicas: 1
  MaxReplicas: 50
AnalyseService:
  RestPort: 8050
  Image: docker.io/midaswr/log-analyse-service:latest
  DNS: log-analyse-src
  DeploymentReplicas: 1
  CpuAverage: 70
  MinReplicas: 1
  MaxReplicas: 50
LLMBaseGPTService:
  RestPort: 8070
  Image: docker.io/midaswr/llm_base_gpt:latest
  DNS: log-llm-gpt-src
  DeploymentReplicas: 1
  CpuAverage: 70
  MinReplicas: 1
  MaxReplicas: 50

Clickhouse:
  PvcStorage: 50Gi
  CHHost: clickhouse-log-c-clickhouse
Kafka:
  KafkaHost: log-k-cluster
