apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{.Values.Gateway.DNS}}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - api.example.com
    - secretName:
       log-gateway-tls
  rules:
      - http:
         paths:
          # gRPC
          - path: /grpc
            pathType: Prefix
            backend:
              service:
                name: {{.Values.Gateway.DNS}}
                port:
                  number: {{.Values.Gateway.gRPCPort}}


          # REST (HTTP)
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{.Values.Gateway.DNS}}
                port:
                  number: {{.Values.Gateway.RestPort}}
